kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc_name
  annotations:
      "helm.sh/resource-policy": keep
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
